### ISSUE TITLE
这个插件控制台报错，好像是跨域问题

### ISSUE THREAD

**Issue by EaMarWi** [ReichtumQian/logseq-plugin-favorite-tree#1]
plugin-e7d0127d.js:39 Uncaught (in promise) DOMException: Blocked a frame with origin "lsp://logseq.io" from accessing a cross-origin frame.
    at a (lsp://logseq.io/logseq-favorite-tree/dist/plugin-e7d0127d.js:39:566)
    at new Promise (<anonymous>)
    at Ii (lsp://logseq.io/logseq-favorite-tree/dist/plugin-e7d0127d.js:39:661)
    at Xr.ol (lsp://logseq.io/logseq-favorite-tree/dist/plugin-e7d0127d.js:45:3375)

**Comment by EaMarWi** [comment]
要是有最新版最好了，找遍全网都没找到。

**Comment by EaMarWi** [comment]
有位大佬(mjtic12)分享了1.2.1版本，加上博主(ReichtumQian)的这段css能用了。
https://github.com/mjtic12/logseq-plugin-favorite-tree

```css
.kef-ft-fav-arrow {
  position: relative;
  right: 0px;  /* 向左移动 */
}

[id^="radix-"] {
  display: none;
}
```
